apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: confluent

resources:
  - ../../base

# Dev environment - reduced replicas for local k3d/laptop
patches:
  # Reduce Kafka to 1 broker for local testing
  - target:
      kind: Kafka
      name: kafka
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  
  # Reduce KRaft controllers to 1 for local testing
  - target:
      kind: KRaftController
      name: kraftcontroller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  
  # Reduce Connect to 1 replica
  - target:
      kind: Connect
      name: connect
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Reduce Kafka Streams app to 1 replica
  - target:
      kind: Deployment
      name: pageview-enricher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
